In [1]:
import numpy as np

In [2]:
x = [[1,2,3],[4,5,6],[7,1,0]]
arr = np.array(x,np.int8)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [3]:
arr.sum(axis=0)     #axis=0 --> means all columns 

array([12,  8,  9])

In [4]:
arr.sum(axis=1)     #axis=1 --> means all rows 

array([ 6, 15,  8])

# Attributes of numpy array

In [5]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [6]:
#Transpose of Matrix
print(arr.T)  

[[1 4 7]
 [2 5 1]
 [3 6 0]]


In [7]:
#iterating each element of Matrix
#arr.flat -- creates an iterator
for i in arr.flat:    
    print(i)      #prints row1 elements first (from left to right) then row2 elements and so on ....

1
2
3
4
5
6
7
1
0


In [8]:
#dimention of an array
print(arr.ndim)  

2


In [9]:
#size of array (total elements in matrix)
print(arr.size)

9


In [10]:
#total byte size of array
print(arr.nbytes)   #will print n bytes as we have used int8 as its datatype while creating arr (each element is of 1 byte(8 bit)) thus 9 bytes

9


# Methods of numpy array

In [11]:
one = np.array([1,2,33,44,555,6,7])
print(one)
print(one.argmax())   #returns the index of max element
print(one.argmin())   #returns the index of min element
print(one.argsort())   #returns the index of elements - in sorted order 
print(one.argmax(axis=0))  #returns the index of the element(starting from 0) of the max element in axis 0 (for 1-d array axis 0 is an entire array)

[  1   2  33  44 555   6   7]
4
0
[0 1 5 6 2 3 4]
4


In [12]:
two = np.array([[11,2,33],[4,88,5]])
print(two)
print("--------")
print(two.argmax())   #returns the index of max element
print("--------")
print(two.argmin())   #returns the index of min element
print("--------")
print(two.argsort())   #returns the index of elements - in sorted order
print("--------")
print(two.argmax(axis=0))  #returns the index of the element(starting from 0) of the max element in axis 0 
print("--------")
print(two.argmax(axis=1))  #returns the index of the element(starting from 0) of the max element in axis 1 
print("--------")
print(two.argsort(axis=1))  #returns the index of elements - in sorted order (for axis 1) (rows)
print("--------")
print(two.ravel())
print("--------")
print(two.reshape(6,1))

[[11  2 33]
 [ 4 88  5]]
--------
4
--------
1
--------
[[1 0 2]
 [0 2 1]]
--------
[0 1 0]
--------
[2 1]
--------
[[1 0 2]
 [0 2 1]]
--------
[11  2 33  4 88  5]
--------
[[11]
 [ 2]
 [33]
 [ 4]
 [88]
 [ 5]]


# Mathematical Operations

In [13]:
#addition
ar1 = np.array( [ [1,1,1] , [2,2,2] , [3,3,3] ] )
ar2 = np.array( [ [10,10,10] , [20,20,20] , [30,30,30] ])
print(ar1)
print("-----------------")
print(ar2)
print("-----------------")
print(ar1+ar2)
print("-----------------")
print(10*(ar1+ar2))
print("-----------------")
print((ar1*ar2))
print("-----------------")
print(np.sqrt(ar2))
print("-----------------")
print(ar1.sum())
print("-----------------")
print(ar1.max())
print("-----------------")
print(ar1.min())

[[1 1 1]
 [2 2 2]
 [3 3 3]]
-----------------
[[10 10 10]
 [20 20 20]
 [30 30 30]]
-----------------
[[11 11 11]
 [22 22 22]
 [33 33 33]]
-----------------
[[110 110 110]
 [220 220 220]
 [330 330 330]]
-----------------
[[10 10 10]
 [40 40 40]
 [90 90 90]]
-----------------
[[3.16227766 3.16227766 3.16227766]
 [4.47213595 4.47213595 4.47213595]
 [5.47722558 5.47722558 5.47722558]]
-----------------
18
-----------------
3
-----------------
1


In [14]:
ar = np.array( [ [1,5,8],[2,9,4],[3,11,0] ] )
print(ar)
print("---------------")


[[ 1  5  8]
 [ 2  9  4]
 [ 3 11  0]]
---------------


In [15]:
np.where(ar>5)  
#returns a tuples of index returns two tuples row tuple and column tuple -you have to combine them 
# example (ans will be (array([0, 1, 2]), array([2, 1, 1])) -- so here 1st element of both the tuple
#i.e. 
#  (0,2)--> value 8 
#  (1,1)--> value 9 
#  (2,1)--> value 11 


(array([0, 1, 2]), array([2, 1, 1]))

In [16]:
print(np.count_nonzero(ar))   #prints count of total non-zero values

8


In [17]:
print(np.nonzero(ar))  #prints index as tuple (1st tuple = row index and 2nd tuple = column index)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))


# checking space consumption difference between python array(which is list) and numpy array

In [18]:
import sys
py_arr = [1,2,3,4]
np_arr = np.array(py_arr)

print( sys.getsizeof(1) * len(py_arr) )
print( np_arr.itemsize * np_arr.size )
print( sys.getsizeof(1))   # for 64 bit os is is 28
print(np_arr.itemsize)     # for 64 bit os is is 8

112
32
28
8


In [19]:
np_arr.tolist()  #converts numpy array to list

[1, 2, 3, 4]